server:
  port: 9000
    #mybatis配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #  reids配置
  redis:
    host: 192.168.1.6
    port: 6379
    password:
    database: 1


mybatis:
  mapper-locations: classpath*:/mappers/*.xml
  type-aliases-package: com.duing.model

