server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath*:/mappers/*.xml
  type-aliases-package: com.duing.model
